language: "en"

reviews:
  profile: "chill"

  auto_review:
    enabled: true
    drafts: false

  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  poem: false

chat:
  auto_reply: true

knowledge_base:
  opt_out: false

path_filters:
  - "!vendor/**"
  - "!node_modules/**"
  - "!bootstrap/cache/**"
  - "!storage/logs/**"
  - "!storage/framework/cache/**"
  - "!storage/framework/sessions/**"
  - "!storage/framework/views/**"
  - "!public/build/**"

early_access: false
